### ISSUE TITLE
The same emails are being sent multiple time to the same customer

### ISSUE THREAD

**Issue by jbalca** [ebizmarts/magento2-mandrill#39] opened 2017-06-21 12:40 UTC
Hi,

We're facing some high severe issues regarding transactional emails. We can't find a pattern but we have clients:
- that are receiving the same order confirmation email several times. This is happening with shipping emails as well.
- We have other clients that don't receive any emails at all.

We can't find a pattern, for the same type of transactional email one api call is being made to mandrill, or several or none..
We don't really understand what is going on.

We're running Magento 2.1.3 and your Mandrill module 3.0.10.

Do you have any idea what might be? Our client is really upset with this situation.

**Comment by Fouad90** [comment] 2017-06-22 12:32
I have the same issue (in multiple websites), but rather in version 3.0.11.
What I've noticed is that order confirmation emails are sent twice.

I downgraded to 3.0.10, it started working again then.

**Comment by avra911** [comment] 2017-07-06 11:39
ping @centerax

**Comment by cchamikara** [comment] 2017-07-10 05:35
Does this have an update , we also getting the same issue with module version 3.0.11 and Magento version 2.0.15

**Comment by ghost** [comment] 2017-07-11 11:36
Also experiencing the issue with module version 3.0.10 and Magento version 2.1.7. For me the problem is occurring in a custom module I use to send shipment emails. When using the shipment sender function in a loop, I just get multiple copies of the first email in the loop:

`$this->shipmentsender->send($shipmentData);`

This has to be related to the email functionality as in the same loop the tracking is assigned under the $shipmentData object which iterates through each email perfectly. Also if I disable the Mandrill extension, the emails are sent correctly.

**Comment by pyostrike** [comment] 2017-07-14 22:42
This was introduced here:
https://github.com/ebizmarts/magento2-mandrill/commit/17ca40fb7e0224bc002fca15f6b35b6effa7465f#diff-8564704260549e71a21bcfaef977ef33
Reverting back to class replacing, instead of plugin can be used to workaround.

**Comment by centerax** [comment] 2017-07-14 23:21
We will take a look on Monday. Thanks

**Comment by centerax** [comment] 2017-07-17 14:36
as per the different comments version 3.0.11 is not the cause because this problem is happening on 3.0.10 as well. correct?

**Comment by avra911** [comment] 2017-07-17 15:55
is happening only in version 3.0.11, while downgrading to 3.0.10 corrects the problem (emails are sent how it should).

@pyostrike pointed exactly to what introduced the problem.



---- On Mon, 17 Jul 2017 17:36:20 +0300 Pablo &lt;notifications@github.com&gt; wrote ----




as per the different comments version 3.0.11 is not the cause because this problem is happening on 3.0.10 as well. correct?

**Comment by centerax** [comment] 2017-07-17 18:33
@jbalca What do you see on your mandrill account under https://mandrillapp.com/settings/api? Do you see multiple api calls for one order? I still cannot replicate this with new order or shipments.

**Comment by pyostrike** [comment] 2017-07-17 21:43
@centerax Hint: try to send more then 1 message per Magento run, for example 'Send to a 2 Friends'.
It's not multiple per message, but 1st message as messages Magento have to send.

**Comment by centerax** [comment] 2017-07-19 12:49
@pyostrike thanks. I have tried and both messages are sent okay. Can you provide logs and/or more information on how to replicate step by step?

**Comment by pyostrike** [comment] 2017-07-19 13:35
@centerax sorry, have no access to mandrill anymore.
I did following as a test:
- opened a product at Magento store.
- pushed a 'Send to a Friend' button.
- in form added 1@1.com as first 'to' address
- then added 2@2.com as second 'to' address
In mandrill api logs there were 2 sent messages, but each to 1@1.com, so it was two api calls, but the object ( message ?) used in both calls was the first created (to 1@1.com)

**Comment by ghost** [comment] 2017-07-19 21:19
As per earlier comment, I'm using 3.0.10 and experiencing the same issue described above with a custom module that sends shipment emails.

Works fine with Mandrill disabled but with Mandrill, the first email in the loop is duplicated x times for each iteration. So I'm not convinced the issue is isolated to 3.0.11...

Mandrill API logs are correct as per the emails being sent, i.e x emails to the first iteration.

**Comment by Silarn** [comment] 2017-07-21 17:11
I'm fairly certain the fix I detail in #37 is also tied to this issue.

I can only guess that different expressions of this issue are being caused by differing PHP or Magento versions.

Do you need me to create a PR with a core fix instead of a separate plugin?

**Comment by centerax** [comment] 2017-07-21 17:12
@Silarn We dont need you to do anything :) if you want to contribute, go for it!

**Comment by centerax** [comment] 2017-07-21 18:21
finally, I was able to replicate.

looking for a solution, will review what @Silarn provided.

**Comment by centerax** [comment] 2017-07-21 19:53
guys, we merged @Silarn PR to `develop`. Can you test and see how it goes?

**Comment by Silarn** [comment] 2017-07-21 20:01
I know this change (as a second module disabling the original plugin and adding essentially the same alternate plugin switching between Transport models) has solved any email dispatch issues I was having after upgrading to 3.0.11. I never noticed any duplicate message problems, but it was only live for a short time before I noticed an issue and pushed a fix.

**Comment by akuzhel** [comment] 2017-07-24 12:04
Hi there.
We are experiencing this issue in our M2 shop also with module version 3.0.11.
Our business logic is to send 3 order confirmation emails to 3 different address. But we received 3 same emails to the 1 address among 3.

We just tried your **develop** branch with #42. This fixed the issue for us.
@centerax we confirm that issue is fixed with #42.

**Closed as completed** 2017-07-24 12:54 UTC
